language: c
compiler:
  - gcc
  - clang
env:
  - TASK=check CONFIG_FLAGS="--enable-Werror --enable-test-Werror --enable-code-coverage"
  - TASK=distcheck
before_install:
  - sudo apt-get install -y gcc-multilib lcov libasan*
  - gem install coveralls-lcov
  - sudo curl -sSL "https://github.com/bufbuild/buf/releases/download/v0.43.1/buf-$(uname -s)-$(uname -m)" -o /usr/local/bin/buf && sudo chmod +x /usr/local/bin/buf
script:
  - autoreconf -iv
  - ./configure $CONFIG_FLAGS
  - make $TASK
after_success:
  - test "x$CC" = "xgcc" -o "x$CC" = "xclang" && make code-coverage-capture && coveralls-lcov asn1c-*-coverage.info
after_failure:
  - find . -name test-suite.log -exec tail -v -n +1 {} +
  - find . -name check-parsing.sh.log -exec tail -v -n +1 {} +
